// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/batch_create_date_spots.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/batch_create_date_spots.go -destination=internal/usecase/mock/batch_create_date_spots.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockSpotFetcher is a mock of SpotFetcher interface.
type MockSpotFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockSpotFetcherMockRecorder
	isgomock struct{}
}

// MockSpotFetcherMockRecorder is the mock recorder for MockSpotFetcher.
type MockSpotFetcherMockRecorder struct {
	mock *MockSpotFetcher
}

// NewMockSpotFetcher creates a new mock instance.
func NewMockSpotFetcher(ctrl *gomock.Controller) *MockSpotFetcher {
	mock := &MockSpotFetcher{ctrl: ctrl}
	mock.recorder = &MockSpotFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotFetcher) EXPECT() *MockSpotFetcherMockRecorder {
	return m.recorder
}

// FetchSpots mocks base method.
func (m *MockSpotFetcher) FetchSpots(ctx context.Context, prefCode, prefectureName string, genreID, count int) ([]usecase.SpotCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSpots", ctx, prefCode, prefectureName, genreID, count)
	ret0, _ := ret[0].([]usecase.SpotCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSpots indicates an expected call of FetchSpots.
func (mr *MockSpotFetcherMockRecorder) FetchSpots(ctx, prefCode, prefectureName, genreID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSpots", reflect.TypeOf((*MockSpotFetcher)(nil).FetchSpots), ctx, prefCode, prefectureName, genreID, count)
}
