// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_date_spot.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_date_spot.go -destination=internal/usecase/mock/create_date_spot.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateDateSpotInputPort is a mock of CreateDateSpotInputPort interface.
type MockCreateDateSpotInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateDateSpotInputPortMockRecorder
	isgomock struct{}
}

// MockCreateDateSpotInputPortMockRecorder is the mock recorder for MockCreateDateSpotInputPort.
type MockCreateDateSpotInputPortMockRecorder struct {
	mock *MockCreateDateSpotInputPort
}

// NewMockCreateDateSpotInputPort creates a new mock instance.
func NewMockCreateDateSpotInputPort(ctrl *gomock.Controller) *MockCreateDateSpotInputPort {
	mock := &MockCreateDateSpotInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateDateSpotInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateDateSpotInputPort) EXPECT() *MockCreateDateSpotInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateDateSpotInputPort) Execute(arg0 context.Context, arg1 usecase.CreateDateSpotInput) (*usecase.CreateDateSpotOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.CreateDateSpotOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateDateSpotInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateDateSpotInputPort)(nil).Execute), arg0, arg1)
}
