// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_date_spot_review.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_date_spot_review.go -destination=internal/usecase/mock/create_date_spot_review.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateDateSpotReviewInputPort is a mock of CreateDateSpotReviewInputPort interface.
type MockCreateDateSpotReviewInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateDateSpotReviewInputPortMockRecorder
	isgomock struct{}
}

// MockCreateDateSpotReviewInputPortMockRecorder is the mock recorder for MockCreateDateSpotReviewInputPort.
type MockCreateDateSpotReviewInputPortMockRecorder struct {
	mock *MockCreateDateSpotReviewInputPort
}

// NewMockCreateDateSpotReviewInputPort creates a new mock instance.
func NewMockCreateDateSpotReviewInputPort(ctrl *gomock.Controller) *MockCreateDateSpotReviewInputPort {
	mock := &MockCreateDateSpotReviewInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateDateSpotReviewInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateDateSpotReviewInputPort) EXPECT() *MockCreateDateSpotReviewInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateDateSpotReviewInputPort) Execute(arg0 context.Context, arg1 usecase.CreateDateSpotReviewInput) (*usecase.CreateDateSpotReviewOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.CreateDateSpotReviewOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateDateSpotReviewInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateDateSpotReviewInputPort)(nil).Execute), arg0, arg1)
}
