// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_relationship.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_relationship.go -destination=internal/usecase/mock/create_relationship.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateRelationshipInputPort is a mock of CreateRelationshipInputPort interface.
type MockCreateRelationshipInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRelationshipInputPortMockRecorder
	isgomock struct{}
}

// MockCreateRelationshipInputPortMockRecorder is the mock recorder for MockCreateRelationshipInputPort.
type MockCreateRelationshipInputPortMockRecorder struct {
	mock *MockCreateRelationshipInputPort
}

// NewMockCreateRelationshipInputPort creates a new mock instance.
func NewMockCreateRelationshipInputPort(ctrl *gomock.Controller) *MockCreateRelationshipInputPort {
	mock := &MockCreateRelationshipInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateRelationshipInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRelationshipInputPort) EXPECT() *MockCreateRelationshipInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRelationshipInputPort) Execute(arg0 context.Context, arg1 usecase.CreateRelationshipInput) (*usecase.CreateRelationshipOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.CreateRelationshipOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRelationshipInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRelationshipInputPort)(nil).Execute), arg0, arg1)
}
