// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/create_course.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/create_course.go -destination=internal/usecase/mock/create_course.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateCourseInputPort is a mock of CreateCourseInputPort interface.
type MockCreateCourseInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateCourseInputPortMockRecorder
	isgomock struct{}
}

// MockCreateCourseInputPortMockRecorder is the mock recorder for MockCreateCourseInputPort.
type MockCreateCourseInputPortMockRecorder struct {
	mock *MockCreateCourseInputPort
}

// NewMockCreateCourseInputPort creates a new mock instance.
func NewMockCreateCourseInputPort(ctrl *gomock.Controller) *MockCreateCourseInputPort {
	mock := &MockCreateCourseInputPort{ctrl: ctrl}
	mock.recorder = &MockCreateCourseInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateCourseInputPort) EXPECT() *MockCreateCourseInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateCourseInputPort) Execute(arg0 context.Context, arg1 usecase.CreateCourseInput) (*usecase.CreateCourseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.CreateCourseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateCourseInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateCourseInputPort)(nil).Execute), arg0, arg1)
}
