// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_date_spot_review.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_date_spot_review.go -destination=internal/usecase/mock/delete_date_spot_review.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteDateSpotReviewInputPort is a mock of DeleteDateSpotReviewInputPort interface.
type MockDeleteDateSpotReviewInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteDateSpotReviewInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteDateSpotReviewInputPortMockRecorder is the mock recorder for MockDeleteDateSpotReviewInputPort.
type MockDeleteDateSpotReviewInputPortMockRecorder struct {
	mock *MockDeleteDateSpotReviewInputPort
}

// NewMockDeleteDateSpotReviewInputPort creates a new mock instance.
func NewMockDeleteDateSpotReviewInputPort(ctrl *gomock.Controller) *MockDeleteDateSpotReviewInputPort {
	mock := &MockDeleteDateSpotReviewInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteDateSpotReviewInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteDateSpotReviewInputPort) EXPECT() *MockDeleteDateSpotReviewInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteDateSpotReviewInputPort) Execute(arg0 context.Context, arg1 usecase.DeleteDateSpotReviewInput) (*usecase.DeleteDateSpotReviewOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.DeleteDateSpotReviewOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteDateSpotReviewInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteDateSpotReviewInputPort)(nil).Execute), arg0, arg1)
}
