// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_date_spot.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_date_spot.go -destination=internal/usecase/mock/delete_date_spot.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteDateSpotInputPort is a mock of DeleteDateSpotInputPort interface.
type MockDeleteDateSpotInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteDateSpotInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteDateSpotInputPortMockRecorder is the mock recorder for MockDeleteDateSpotInputPort.
type MockDeleteDateSpotInputPortMockRecorder struct {
	mock *MockDeleteDateSpotInputPort
}

// NewMockDeleteDateSpotInputPort creates a new mock instance.
func NewMockDeleteDateSpotInputPort(ctrl *gomock.Controller) *MockDeleteDateSpotInputPort {
	mock := &MockDeleteDateSpotInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteDateSpotInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteDateSpotInputPort) EXPECT() *MockDeleteDateSpotInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteDateSpotInputPort) Execute(arg0 context.Context, arg1 usecase.DeleteDateSpotInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteDateSpotInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteDateSpotInputPort)(nil).Execute), arg0, arg1)
}
