// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_user.go -destination=internal/usecase/mock/delete_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteUserInputPort is a mock of DeleteUserInputPort interface.
type MockDeleteUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteUserInputPortMockRecorder is the mock recorder for MockDeleteUserInputPort.
type MockDeleteUserInputPortMockRecorder struct {
	mock *MockDeleteUserInputPort
}

// NewMockDeleteUserInputPort creates a new mock instance.
func NewMockDeleteUserInputPort(ctrl *gomock.Controller) *MockDeleteUserInputPort {
	mock := &MockDeleteUserInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUserInputPort) EXPECT() *MockDeleteUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteUserInputPort) Execute(arg0 context.Context, arg1 usecase.DeleteUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteUserInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteUserInputPort)(nil).Execute), arg0, arg1)
}
