// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_relationship.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_relationship.go -destination=internal/usecase/mock/delete_relationship.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteRelationshipInputPort is a mock of DeleteRelationshipInputPort interface.
type MockDeleteRelationshipInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteRelationshipInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteRelationshipInputPortMockRecorder is the mock recorder for MockDeleteRelationshipInputPort.
type MockDeleteRelationshipInputPortMockRecorder struct {
	mock *MockDeleteRelationshipInputPort
}

// NewMockDeleteRelationshipInputPort creates a new mock instance.
func NewMockDeleteRelationshipInputPort(ctrl *gomock.Controller) *MockDeleteRelationshipInputPort {
	mock := &MockDeleteRelationshipInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteRelationshipInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteRelationshipInputPort) EXPECT() *MockDeleteRelationshipInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteRelationshipInputPort) Execute(arg0 context.Context, arg1 usecase.DeleteRelationshipInput) (*usecase.DeleteRelationshipOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.DeleteRelationshipOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteRelationshipInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteRelationshipInputPort)(nil).Execute), arg0, arg1)
}
