// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/delete_course.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/delete_course.go -destination=internal/usecase/mock/delete_course.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteCourseInputPort is a mock of DeleteCourseInputPort interface.
type MockDeleteCourseInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteCourseInputPortMockRecorder
	isgomock struct{}
}

// MockDeleteCourseInputPortMockRecorder is the mock recorder for MockDeleteCourseInputPort.
type MockDeleteCourseInputPortMockRecorder struct {
	mock *MockDeleteCourseInputPort
}

// NewMockDeleteCourseInputPort creates a new mock instance.
func NewMockDeleteCourseInputPort(ctrl *gomock.Controller) *MockDeleteCourseInputPort {
	mock := &MockDeleteCourseInputPort{ctrl: ctrl}
	mock.recorder = &MockDeleteCourseInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteCourseInputPort) EXPECT() *MockDeleteCourseInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteCourseInputPort) Execute(arg0 context.Context, arg1 usecase.DeleteCourseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteCourseInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteCourseInputPort)(nil).Execute), arg0, arg1)
}
