// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_user.go -destination=internal/usecase/mock/get_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserInputPort is a mock of GetUserInputPort interface.
type MockGetUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserInputPortMockRecorder
	isgomock struct{}
}

// MockGetUserInputPortMockRecorder is the mock recorder for MockGetUserInputPort.
type MockGetUserInputPortMockRecorder struct {
	mock *MockGetUserInputPort
}

// NewMockGetUserInputPort creates a new mock instance.
func NewMockGetUserInputPort(ctrl *gomock.Controller) *MockGetUserInputPort {
	mock := &MockGetUserInputPort{ctrl: ctrl}
	mock.recorder = &MockGetUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserInputPort) EXPECT() *MockGetUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserInputPort) Execute(arg0 context.Context, arg1 usecase.GetUserInput) (*usecase.GetUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserInputPort)(nil).Execute), arg0, arg1)
}
