// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_user_followers.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_user_followers.go -destination=internal/usecase/mock/get_user_followers.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserFollowersInputPort is a mock of GetUserFollowersInputPort interface.
type MockGetUserFollowersInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserFollowersInputPortMockRecorder
	isgomock struct{}
}

// MockGetUserFollowersInputPortMockRecorder is the mock recorder for MockGetUserFollowersInputPort.
type MockGetUserFollowersInputPortMockRecorder struct {
	mock *MockGetUserFollowersInputPort
}

// NewMockGetUserFollowersInputPort creates a new mock instance.
func NewMockGetUserFollowersInputPort(ctrl *gomock.Controller) *MockGetUserFollowersInputPort {
	mock := &MockGetUserFollowersInputPort{ctrl: ctrl}
	mock.recorder = &MockGetUserFollowersInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserFollowersInputPort) EXPECT() *MockGetUserFollowersInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserFollowersInputPort) Execute(arg0 context.Context, arg1 usecase.GetUserFollowersInput) (*usecase.GetUserFollowersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetUserFollowersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserFollowersInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserFollowersInputPort)(nil).Execute), arg0, arg1)
}
