// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_date_spots.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_date_spots.go -destination=internal/usecase/mock/get_date_spots.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetDateSpotsInputPort is a mock of GetDateSpotsInputPort interface.
type MockGetDateSpotsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetDateSpotsInputPortMockRecorder
	isgomock struct{}
}

// MockGetDateSpotsInputPortMockRecorder is the mock recorder for MockGetDateSpotsInputPort.
type MockGetDateSpotsInputPortMockRecorder struct {
	mock *MockGetDateSpotsInputPort
}

// NewMockGetDateSpotsInputPort creates a new mock instance.
func NewMockGetDateSpotsInputPort(ctrl *gomock.Controller) *MockGetDateSpotsInputPort {
	mock := &MockGetDateSpotsInputPort{ctrl: ctrl}
	mock.recorder = &MockGetDateSpotsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetDateSpotsInputPort) EXPECT() *MockGetDateSpotsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetDateSpotsInputPort) Execute(arg0 context.Context, arg1 usecase.GetDateSpotsInput) (*usecase.GetDateSpotsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetDateSpotsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetDateSpotsInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetDateSpotsInputPort)(nil).Execute), arg0, arg1)
}
