// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_date_spot.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_date_spot.go -destination=internal/usecase/mock/get_date_spot.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetDateSpotInputPort is a mock of GetDateSpotInputPort interface.
type MockGetDateSpotInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetDateSpotInputPortMockRecorder
	isgomock struct{}
}

// MockGetDateSpotInputPortMockRecorder is the mock recorder for MockGetDateSpotInputPort.
type MockGetDateSpotInputPortMockRecorder struct {
	mock *MockGetDateSpotInputPort
}

// NewMockGetDateSpotInputPort creates a new mock instance.
func NewMockGetDateSpotInputPort(ctrl *gomock.Controller) *MockGetDateSpotInputPort {
	mock := &MockGetDateSpotInputPort{ctrl: ctrl}
	mock.recorder = &MockGetDateSpotInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetDateSpotInputPort) EXPECT() *MockGetDateSpotInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetDateSpotInputPort) Execute(arg0 context.Context, arg1 usecase.GetDateSpotInput) (*usecase.GetDateSpotOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetDateSpotOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetDateSpotInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetDateSpotInputPort)(nil).Execute), arg0, arg1)
}
