// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_user_followings.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_user_followings.go -destination=internal/usecase/mock/get_user_followings.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUserFollowingsInputPort is a mock of GetUserFollowingsInputPort interface.
type MockGetUserFollowingsInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserFollowingsInputPortMockRecorder
	isgomock struct{}
}

// MockGetUserFollowingsInputPortMockRecorder is the mock recorder for MockGetUserFollowingsInputPort.
type MockGetUserFollowingsInputPortMockRecorder struct {
	mock *MockGetUserFollowingsInputPort
}

// NewMockGetUserFollowingsInputPort creates a new mock instance.
func NewMockGetUserFollowingsInputPort(ctrl *gomock.Controller) *MockGetUserFollowingsInputPort {
	mock := &MockGetUserFollowingsInputPort{ctrl: ctrl}
	mock.recorder = &MockGetUserFollowingsInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserFollowingsInputPort) EXPECT() *MockGetUserFollowingsInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserFollowingsInputPort) Execute(arg0 context.Context, arg1 usecase.GetUserFollowingsInput) (*usecase.GetUserFollowingsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetUserFollowingsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserFollowingsInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserFollowingsInputPort)(nil).Execute), arg0, arg1)
}
