// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_courses.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_courses.go -destination=internal/usecase/mock/get_courses.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetCoursesInputPort is a mock of GetCoursesInputPort interface.
type MockGetCoursesInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetCoursesInputPortMockRecorder
	isgomock struct{}
}

// MockGetCoursesInputPortMockRecorder is the mock recorder for MockGetCoursesInputPort.
type MockGetCoursesInputPortMockRecorder struct {
	mock *MockGetCoursesInputPort
}

// NewMockGetCoursesInputPort creates a new mock instance.
func NewMockGetCoursesInputPort(ctrl *gomock.Controller) *MockGetCoursesInputPort {
	mock := &MockGetCoursesInputPort{ctrl: ctrl}
	mock.recorder = &MockGetCoursesInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCoursesInputPort) EXPECT() *MockGetCoursesInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetCoursesInputPort) Execute(arg0 context.Context, arg1 usecase.GetCoursesInput) (*usecase.GetCoursesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetCoursesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetCoursesInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetCoursesInputPort)(nil).Execute), arg0, arg1)
}
