// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_users.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_users.go -destination=internal/usecase/mock/get_users.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetUsersInputPort is a mock of GetUsersInputPort interface.
type MockGetUsersInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetUsersInputPortMockRecorder
	isgomock struct{}
}

// MockGetUsersInputPortMockRecorder is the mock recorder for MockGetUsersInputPort.
type MockGetUsersInputPortMockRecorder struct {
	mock *MockGetUsersInputPort
}

// NewMockGetUsersInputPort creates a new mock instance.
func NewMockGetUsersInputPort(ctrl *gomock.Controller) *MockGetUsersInputPort {
	mock := &MockGetUsersInputPort{ctrl: ctrl}
	mock.recorder = &MockGetUsersInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUsersInputPort) EXPECT() *MockGetUsersInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUsersInputPort) Execute(arg0 context.Context, arg1 usecase.GetUsersInput) (*usecase.GetUsersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUsersInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUsersInputPort)(nil).Execute), arg0, arg1)
}
