// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_course.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_course.go -destination=internal/usecase/mock/get_course.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetCourseInputPort is a mock of GetCourseInputPort interface.
type MockGetCourseInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetCourseInputPortMockRecorder
	isgomock struct{}
}

// MockGetCourseInputPortMockRecorder is the mock recorder for MockGetCourseInputPort.
type MockGetCourseInputPortMockRecorder struct {
	mock *MockGetCourseInputPort
}

// NewMockGetCourseInputPort creates a new mock instance.
func NewMockGetCourseInputPort(ctrl *gomock.Controller) *MockGetCourseInputPort {
	mock := &MockGetCourseInputPort{ctrl: ctrl}
	mock.recorder = &MockGetCourseInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCourseInputPort) EXPECT() *MockGetCourseInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetCourseInputPort) Execute(arg0 context.Context, arg1 usecase.GetCourseInput) (*usecase.GetCourseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.GetCourseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetCourseInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetCourseInputPort)(nil).Execute), arg0, arg1)
}
