// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/login.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/login.go -destination=internal/usecase/mock/login.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginInputPort is a mock of LoginInputPort interface.
type MockLoginInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockLoginInputPortMockRecorder
	isgomock struct{}
}

// MockLoginInputPortMockRecorder is the mock recorder for MockLoginInputPort.
type MockLoginInputPortMockRecorder struct {
	mock *MockLoginInputPort
}

// NewMockLoginInputPort creates a new mock instance.
func NewMockLoginInputPort(ctrl *gomock.Controller) *MockLoginInputPort {
	mock := &MockLoginInputPort{ctrl: ctrl}
	mock.recorder = &MockLoginInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginInputPort) EXPECT() *MockLoginInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginInputPort) Execute(arg0 context.Context, arg1 usecase.LoginInput) (*usecase.LoginOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.LoginOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginInputPort)(nil).Execute), arg0, arg1)
}
