// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/signup.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/signup.go -destination=internal/usecase/mock/signup.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockSignupInputPort is a mock of SignupInputPort interface.
type MockSignupInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSignupInputPortMockRecorder
	isgomock struct{}
}

// MockSignupInputPortMockRecorder is the mock recorder for MockSignupInputPort.
type MockSignupInputPortMockRecorder struct {
	mock *MockSignupInputPort
}

// NewMockSignupInputPort creates a new mock instance.
func NewMockSignupInputPort(ctrl *gomock.Controller) *MockSignupInputPort {
	mock := &MockSignupInputPort{ctrl: ctrl}
	mock.recorder = &MockSignupInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignupInputPort) EXPECT() *MockSignupInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSignupInputPort) Execute(arg0 context.Context, arg1 usecase.SignupInput) (*usecase.SignupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.SignupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSignupInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSignupInputPort)(nil).Execute), arg0, arg1)
}
