// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_date_spot_review.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_date_spot_review.go -destination=internal/usecase/mock/update_date_spot_review.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateDateSpotReviewInputPort is a mock of UpdateDateSpotReviewInputPort interface.
type MockUpdateDateSpotReviewInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateDateSpotReviewInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateDateSpotReviewInputPortMockRecorder is the mock recorder for MockUpdateDateSpotReviewInputPort.
type MockUpdateDateSpotReviewInputPortMockRecorder struct {
	mock *MockUpdateDateSpotReviewInputPort
}

// NewMockUpdateDateSpotReviewInputPort creates a new mock instance.
func NewMockUpdateDateSpotReviewInputPort(ctrl *gomock.Controller) *MockUpdateDateSpotReviewInputPort {
	mock := &MockUpdateDateSpotReviewInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateDateSpotReviewInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateDateSpotReviewInputPort) EXPECT() *MockUpdateDateSpotReviewInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateDateSpotReviewInputPort) Execute(arg0 context.Context, arg1 usecase.UpdateDateSpotReviewInput) (*usecase.UpdateDateSpotReviewOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.UpdateDateSpotReviewOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateDateSpotReviewInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateDateSpotReviewInputPort)(nil).Execute), arg0, arg1)
}
