// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_date_spot.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_date_spot.go -destination=internal/usecase/mock/update_date_spot.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateDateSpotInputPort is a mock of UpdateDateSpotInputPort interface.
type MockUpdateDateSpotInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateDateSpotInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateDateSpotInputPortMockRecorder is the mock recorder for MockUpdateDateSpotInputPort.
type MockUpdateDateSpotInputPortMockRecorder struct {
	mock *MockUpdateDateSpotInputPort
}

// NewMockUpdateDateSpotInputPort creates a new mock instance.
func NewMockUpdateDateSpotInputPort(ctrl *gomock.Controller) *MockUpdateDateSpotInputPort {
	mock := &MockUpdateDateSpotInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateDateSpotInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateDateSpotInputPort) EXPECT() *MockUpdateDateSpotInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateDateSpotInputPort) Execute(arg0 context.Context, arg1 usecase.UpdateDateSpotInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateDateSpotInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateDateSpotInputPort)(nil).Execute), arg0, arg1)
}
