// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/update_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/update_user.go -destination=internal/usecase/mock/update_user.go -package=usecasemock
//

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/daisuke-harada/date-courses-go/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateUserInputPort is a mock of UpdateUserInputPort interface.
type MockUpdateUserInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateUserInputPortMockRecorder
	isgomock struct{}
}

// MockUpdateUserInputPortMockRecorder is the mock recorder for MockUpdateUserInputPort.
type MockUpdateUserInputPortMockRecorder struct {
	mock *MockUpdateUserInputPort
}

// NewMockUpdateUserInputPort creates a new mock instance.
func NewMockUpdateUserInputPort(ctrl *gomock.Controller) *MockUpdateUserInputPort {
	mock := &MockUpdateUserInputPort{ctrl: ctrl}
	mock.recorder = &MockUpdateUserInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateUserInputPort) EXPECT() *MockUpdateUserInputPortMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateUserInputPort) Execute(arg0 context.Context, arg1 usecase.UpdateUserInput) (*usecase.UpdateUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*usecase.UpdateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateUserInputPortMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateUserInputPort)(nil).Execute), arg0, arg1)
}
