// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/user_service.go -destination=internal/domain/service/mock/user_service.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// BuildUserWithRelations mocks base method.
func (m *MockUserService) BuildUserWithRelations(ctx context.Context, user *model.User) (*model.UserWithRelations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildUserWithRelations", ctx, user)
	ret0, _ := ret[0].(*model.UserWithRelations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildUserWithRelations indicates an expected call of BuildUserWithRelations.
func (mr *MockUserServiceMockRecorder) BuildUserWithRelations(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildUserWithRelations", reflect.TypeOf((*MockUserService)(nil).BuildUserWithRelations), ctx, user)
}

// BuildUsersWithRelations mocks base method.
func (m *MockUserService) BuildUsersWithRelations(ctx context.Context, users []*model.User) ([]*model.UserWithRelations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildUsersWithRelations", ctx, users)
	ret0, _ := ret[0].([]*model.UserWithRelations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildUsersWithRelations indicates an expected call of BuildUsersWithRelations.
func (mr *MockUserServiceMockRecorder) BuildUsersWithRelations(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildUsersWithRelations", reflect.TypeOf((*MockUserService)(nil).BuildUsersWithRelations), ctx, users)
}
