// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CourseFormRequestDataAuthority.
const (
	Empty CourseFormRequestDataAuthority = "公開"
	N1    CourseFormRequestDataAuthority = "非公開"
)

// Defines values for CourseFormRequestDataTravelMode.
const (
	DRIVING CourseFormRequestDataTravelMode = "DRIVING"
	WALKING CourseFormRequestDataTravelMode = "WALKING"
)

// AddressAndDateSpotsData defines model for AddressAndDateSpotsData.
type AddressAndDateSpotsData struct {
	AverageRate       float32      `json:"average_rate"`
	CityName          string       `json:"city_name"`
	DateSpot          DateSpotData `json:"date_spot"`
	GenreName         string       `json:"genre_name"`
	Id                int          `json:"id"`
	Latitude          float32      `json:"latitude"`
	Longitude         float32      `json:"longitude"`
	PrefectureName    string       `json:"prefecture_name"`
	ReviewTotalNumber int          `json:"review_total_number"`
}

// CourseFormRequestData defines model for CourseFormRequestData.
type CourseFormRequestData struct {
	Authority  CourseFormRequestDataAuthority  `json:"authority"`
	DateSpots  []int                           `json:"date_spots"`
	TravelMode CourseFormRequestDataTravelMode `json:"travel_mode"`
	UserId     int                             `json:"user_id"`
}

// CourseFormRequestDataAuthority defines model for CourseFormRequestData.Authority.
type CourseFormRequestDataAuthority string

// CourseFormRequestDataTravelMode defines model for CourseFormRequestData.TravelMode.
type CourseFormRequestDataTravelMode string

// CourseFormResponseData defines model for CourseFormResponseData.
type CourseFormResponseData struct {
	DateSpotId *int `json:"date_spot_id,omitempty"`
}

// CourseResponseData defines model for CourseResponseData.
type CourseResponseData struct {
	Authority                  string                    `json:"authority"`
	DateSpots                  []AddressAndDateSpotsData `json:"date_spots"`
	Id                         int                       `json:"id"`
	NoDuplicatePrefectureNames []string                  `json:"no_duplicate_prefecture_names"`
	TravelMode                 string                    `json:"travel_mode"`
	User                       UserData                  `json:"user"`
}

// CourseSortRequestData defines model for CourseSortRequestData.
type CourseSortRequestData struct {
	PrefectureId int `json:"prefecture_id"`
}

// CourseSortResponseData defines model for CourseSortResponseData.
type CourseSortResponseData struct {
	Courses      []CourseResponseData `json:"courses"`
	PrefectureId int                  `json:"prefecture_id"`
}

// DateSpotData defines model for DateSpotData.
type DateSpotData struct {
	AverageRate float32   `json:"average_rate"`
	ClosingTime time.Time `json:"closing_time"`
	CreatedAt   time.Time `json:"created_at"`
	GenreId     int       `json:"genre_id"`
	Id          int       `json:"id"`
	Image       ImageData `json:"image"`
	Name        string    `json:"name"`
	OpeningTime time.Time `json:"opening_time"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// DateSpotFormRequestData defines model for DateSpotFormRequestData.
type DateSpotFormRequestData struct {
	CityName     string     `json:"city_name"`
	ClosingTime  time.Time  `json:"closing_time"`
	GenreId      int        `json:"genre_id"`
	Image        ImageData1 `json:"image"`
	Name         string     `json:"name"`
	OpeningTime  time.Time  `json:"opening_time"`
	PrefectureId int        `json:"prefecture_id"`
}

// DateSpotFormResponseData defines model for DateSpotFormResponseData.
type DateSpotFormResponseData struct {
	DateSpotId int `json:"date_spot_id"`
}

// DateSpotNameSearchData defines model for DateSpotNameSearchData.
type DateSpotNameSearchData struct {
	DateSpotName string `json:"date_spot_name"`
}

// DateSpotReviewData defines model for DateSpotReviewData.
type DateSpotReviewData struct {
	Content  string       `json:"content"`
	DateSpot DateSpotData `json:"date_spot"`
	Id       int          `json:"id"`
	Rate     float32      `json:"rate"`
}

// DateSpotReviewFormRequestData defines model for DateSpotReviewFormRequestData.
type DateSpotReviewFormRequestData struct {
	Content    string  `json:"content"`
	DateSpotId int     `json:"date_spot_id"`
	Rate       float32 `json:"rate"`
	UserId     int     `json:"user_id"`
}

// DateSpotReviewResponseData defines model for DateSpotReviewResponseData.
type DateSpotReviewResponseData struct {
	DateSpotReviews   []DateSpotReviewResponseDataDateSpotReviewsInner `json:"date_spot_reviews"`
	ReviewAverageRate int                                              `json:"review_average_rate"`
}

// DateSpotReviewResponseDataDateSpotReviewsInner defines model for DateSpotReviewResponseData_date_spot_reviews_inner.
type DateSpotReviewResponseDataDateSpotReviewsInner struct {
	Content    string    `json:"content"`
	DateSpotId int       `json:"date_spot_id"`
	Id         int       `json:"id"`
	Rate       float32   `json:"rate"`
	UserGender string    `json:"user_gender"`
	UserId     int       `json:"user_id"`
	UserImage  ImageData `json:"user_image"`
	UserName   string    `json:"user_name"`
}

// DateSpotSortData defines model for DateSpotSortData.
type DateSpotSortData struct {
	ComeTime     time.Time `json:"come_time"`
	GenreId      int       `json:"genre_id"`
	PrefectureId int       `json:"prefecture_id"`
}

// DateSpotSortResponseData defines model for DateSpotSortResponseData.
type DateSpotSortResponseData struct {
	AddressAndDateSpots []AddressAndDateSpotsData `json:"address_and_date_spots"`
	ComeTime            time.Time                 `json:"come_time"`
	GenreId             int                       `json:"genre_id"`
	PrefectureId        int                       `json:"prefecture_id"`
}

// FollowReauestData defines model for FollowReauestData.
type FollowReauestData struct {
	CurrentUserId  int `json:"current_user_id"`
	FollowedUserId int `json:"followed_user_id"`
}

// FollowResponseData defines model for FollowResponseData.
type FollowResponseData struct {
	CurrentUser  UserResponseData   `json:"current_user"`
	FollowedUser UserResponseData   `json:"followed_user"`
	Users        []UserResponseData `json:"users"`
}

// ImageData defines model for ImageData.
type ImageData struct {
	Url *string `json:"url"`
}

// ImageData1 defines model for ImageData_1.
type ImageData1 struct {
	Url *openapi_types.File `json:"url"`
}

// LoginResponseData defines model for LoginResponseData.
type LoginResponseData struct {
	LoginStatus bool `json:"login_status"`
}

// RelationShipResponsData defines model for RelationShipResponsData.
type RelationShipResponsData struct {
	UserName string             `json:"user_name"`
	Users    []UserResponseData `json:"users"`
}

// SignUpResponseData defines model for SignUpResponseData.
type SignUpResponseData struct {
	LoginStatus bool        `json:"login_status"`
	User        interface{} `json:"user"`
}

// SigninFormRequestData defines model for SigninFormRequestData.
type SigninFormRequestData struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// SignupFormRequestData defines model for SignupFormRequestData.
type SignupFormRequestData struct {
	Email                string              `json:"email"`
	Gender               string              `json:"gender"`
	Image                *openapi_types.File `json:"image,omitempty"`
	Name                 string              `json:"name"`
	Password             string              `json:"password"`
	PasswordConfirmation string              `json:"password_confirmation"`
}

// TopResponseData defines model for TopResponseData.
type TopResponseData struct {
	AddressAndDateSpots []AddressAndDateSpotsData `json:"address_and_date_spots"`
	Areas               string                    `json:"areas"`
	Genres              string                    `json:"genres"`
	MainGenres          string                    `json:"main_genres"`
	MainPrefecture      string                    `json:"main_prefecture"`
}

// UserData defines model for UserData.
type UserData struct {
	Admin  bool                `json:"admin"`
	Email  openapi_types.Email `json:"email"`
	Gender string              `json:"gender"`
	Id     int                 `json:"id"`
	Image  ImageData           `json:"image"`
	Name   string              `json:"name"`
}

// UserFormRequestData defines model for UserFormRequestData.
type UserFormRequestData struct {
	Email                openapi_types.Email `json:"email"`
	Gender               string              `json:"gender"`
	Id                   string              `json:"id"`
	Image                *openapi_types.File `json:"image,omitempty"`
	Name                 string              `json:"name"`
	Password             string              `json:"password"`
	PasswordConfirmation string              `json:"password_confirmation"`
}

// UserNameSearchData defines model for UserNameSearchData.
type UserNameSearchData struct {
	UserName string `json:"user_name"`
}

// UserResponseData defines model for UserResponseData.
type UserResponseData struct {
	Admin           bool                 `json:"admin"`
	Courses         []CourseResponseData `json:"courses"`
	DateSpotReviews []DateSpotReviewData `json:"date_spot_reviews"`
	Email           string               `json:"email"`
	FollowerIds     []int                `json:"followerIds"`
	FollowingIds    []int                `json:"followingIds"`
	Gender          string               `json:"gender"`
	Id              int                  `json:"id"`
	Image           ImageData            `json:"image"`
	Name            string               `json:"name"`
}

// WelcomeResponseData defines model for WelcomeResponseData.
type WelcomeResponseData struct {
	Message string `json:"message"`
}

// PostApiV1CoursesFormdataRequestBody defines body for PostApiV1Courses for application/x-www-form-urlencoded ContentType.
type PostApiV1CoursesFormdataRequestBody = CourseFormRequestData

// PostApiV1CoursesSortFormdataRequestBody defines body for PostApiV1CoursesSort for application/x-www-form-urlencoded ContentType.
type PostApiV1CoursesSortFormdataRequestBody = CourseSortRequestData

// PostApiV1DateSpotNameSearchFormdataRequestBody defines body for PostApiV1DateSpotNameSearch for application/x-www-form-urlencoded ContentType.
type PostApiV1DateSpotNameSearchFormdataRequestBody = DateSpotNameSearchData

// PostApiV1DateSpotReviewsMultipartRequestBody defines body for PostApiV1DateSpotReviews for multipart/form-data ContentType.
type PostApiV1DateSpotReviewsMultipartRequestBody = DateSpotReviewFormRequestData

// PutApiV1DateSpotReviewsIdMultipartRequestBody defines body for PutApiV1DateSpotReviewsId for multipart/form-data ContentType.
type PutApiV1DateSpotReviewsIdMultipartRequestBody = DateSpotReviewFormRequestData

// PostApiV1DateSpotsMultipartRequestBody defines body for PostApiV1DateSpots for multipart/form-data ContentType.
type PostApiV1DateSpotsMultipartRequestBody = DateSpotFormRequestData

// PostApiV1DateSpotsSortFormdataRequestBody defines body for PostApiV1DateSpotsSort for application/x-www-form-urlencoded ContentType.
type PostApiV1DateSpotsSortFormdataRequestBody = DateSpotSortData

// PutApiV1DateSpotsIdMultipartRequestBody defines body for PutApiV1DateSpotsId for multipart/form-data ContentType.
type PutApiV1DateSpotsIdMultipartRequestBody = DateSpotFormRequestData

// PostApiV1LoginFormdataRequestBody defines body for PostApiV1Login for application/x-www-form-urlencoded ContentType.
type PostApiV1LoginFormdataRequestBody = SigninFormRequestData

// PostApiV1RelationshipsFormdataRequestBody defines body for PostApiV1Relationships for application/x-www-form-urlencoded ContentType.
type PostApiV1RelationshipsFormdataRequestBody = FollowReauestData

// PostApiV1SignupMultipartRequestBody defines body for PostApiV1Signup for multipart/form-data ContentType.
type PostApiV1SignupMultipartRequestBody = SignupFormRequestData

// PostApiV1UserNameSearchFormdataRequestBody defines body for PostApiV1UserNameSearch for application/x-www-form-urlencoded ContentType.
type PostApiV1UserNameSearchFormdataRequestBody = UserNameSearchData

// PutApiV1UsersIdMultipartRequestBody defines body for PutApiV1UsersId for multipart/form-data ContentType.
type PutApiV1UsersIdMultipartRequestBody = UserFormRequestData
