components:
  schemas:
    WelcomeResponseData:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "hello"
    TopResponseData:
      type: object
      required:
        - date_spots
        - areas
        - genres
        - main_genres
        - main_prefectures
      properties:
        date_spots:
          type: array
          items:
           $ref: "./date_spot_summary_data.yaml#/components/schemas/DateSpotSummaryData"
        areas:
          type: array
          items:
            $ref: "./area.yaml#/components/schemas/AreaData"
        genres:
          type: array
          items:
            $ref: "./genre.yaml#/components/schemas/GenreData"
        main_genres:
          type: array
          items:
            $ref: "./genre.yaml#/components/schemas/GenreData"
        main_prefectures:
          type: array
          items:
            $ref: "./prefecture.yaml#/components/schemas/PrefectureData"