// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/course_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/course_repository.go -destination=internal/domain/repository/mock/course_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	repository "github.com/daisuke-harada/date-courses-go/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockCourseRepository is a mock of CourseRepository interface.
type MockCourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourseRepositoryMockRecorder
	isgomock struct{}
}

// MockCourseRepositoryMockRecorder is the mock recorder for MockCourseRepository.
type MockCourseRepositoryMockRecorder struct {
	mock *MockCourseRepository
}

// NewMockCourseRepository creates a new mock instance.
func NewMockCourseRepository(ctrl *gomock.Controller) *MockCourseRepository {
	mock := &MockCourseRepository{ctrl: ctrl}
	mock.recorder = &MockCourseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseRepository) EXPECT() *MockCourseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourseRepository) Create(ctx context.Context, course *model.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, course)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCourseRepositoryMockRecorder) Create(ctx, course any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourseRepository)(nil).Create), ctx, course)
}

// DeleteByID mocks base method.
func (m *MockCourseRepository) DeleteByID(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockCourseRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockCourseRepository)(nil).DeleteByID), ctx, id)
}

// FindAllByUserID mocks base method.
func (m *MockCourseRepository) FindAllByUserID(ctx context.Context, userID uint) ([]*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockCourseRepositoryMockRecorder) FindAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockCourseRepository)(nil).FindAllByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockCourseRepository) FindByID(ctx context.Context, id, viewerID uint) (*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, viewerID)
	ret0, _ := ret[0].(*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCourseRepositoryMockRecorder) FindByID(ctx, id, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCourseRepository)(nil).FindByID), ctx, id, viewerID)
}

// FindPublicByUserIDs mocks base method.
func (m *MockCourseRepository) FindPublicByUserIDs(ctx context.Context, userIDs []uint) (map[uint][]*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublicByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[uint][]*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublicByUserIDs indicates an expected call of FindPublicByUserIDs.
func (mr *MockCourseRepositoryMockRecorder) FindPublicByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublicByUserIDs", reflect.TypeOf((*MockCourseRepository)(nil).FindPublicByUserIDs), ctx, userIDs)
}

// Search mocks base method.
func (m *MockCourseRepository) Search(ctx context.Context, params repository.CourseSearchParams) ([]*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].([]*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCourseRepositoryMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCourseRepository)(nil).Search), ctx, params)
}
