// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/date_spot_review_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/date_spot_review_repository.go -destination=internal/domain/repository/mock/date_spot_review_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDateSpotReviewRepository is a mock of DateSpotReviewRepository interface.
type MockDateSpotReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDateSpotReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockDateSpotReviewRepositoryMockRecorder is the mock recorder for MockDateSpotReviewRepository.
type MockDateSpotReviewRepositoryMockRecorder struct {
	mock *MockDateSpotReviewRepository
}

// NewMockDateSpotReviewRepository creates a new mock instance.
func NewMockDateSpotReviewRepository(ctrl *gomock.Controller) *MockDateSpotReviewRepository {
	mock := &MockDateSpotReviewRepository{ctrl: ctrl}
	mock.recorder = &MockDateSpotReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDateSpotReviewRepository) EXPECT() *MockDateSpotReviewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDateSpotReviewRepository) Create(ctx context.Context, review *model.DateSpotReview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDateSpotReviewRepositoryMockRecorder) Create(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).Create), ctx, review)
}

// DeleteByID mocks base method.
func (m *MockDateSpotReviewRepository) DeleteByID(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockDateSpotReviewRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).DeleteByID), ctx, id)
}

// FindByDateSpotID mocks base method.
func (m *MockDateSpotReviewRepository) FindByDateSpotID(ctx context.Context, dateSpotID uint) ([]*model.DateSpotReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDateSpotID", ctx, dateSpotID)
	ret0, _ := ret[0].([]*model.DateSpotReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDateSpotID indicates an expected call of FindByDateSpotID.
func (mr *MockDateSpotReviewRepositoryMockRecorder) FindByDateSpotID(ctx, dateSpotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDateSpotID", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).FindByDateSpotID), ctx, dateSpotID)
}

// FindByID mocks base method.
func (m *MockDateSpotReviewRepository) FindByID(ctx context.Context, id uint) (*model.DateSpotReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.DateSpotReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDateSpotReviewRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockDateSpotReviewRepository) FindByUserID(ctx context.Context, userID uint) ([]*model.DateSpotReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.DateSpotReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockDateSpotReviewRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).FindByUserID), ctx, userID)
}

// UpdateByID mocks base method.
func (m *MockDateSpotReviewRepository) UpdateByID(ctx context.Context, id uint, review *model.DateSpotReview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockDateSpotReviewRepositoryMockRecorder) UpdateByID(ctx, id, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockDateSpotReviewRepository)(nil).UpdateByID), ctx, id, review)
}
