// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/date_spot_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/date_spot_repository.go -destination=internal/domain/repository/mock/date_spot_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	repository "github.com/daisuke-harada/date-courses-go/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDateSpotRepository is a mock of DateSpotRepository interface.
type MockDateSpotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDateSpotRepositoryMockRecorder
	isgomock struct{}
}

// MockDateSpotRepositoryMockRecorder is the mock recorder for MockDateSpotRepository.
type MockDateSpotRepositoryMockRecorder struct {
	mock *MockDateSpotRepository
}

// NewMockDateSpotRepository creates a new mock instance.
func NewMockDateSpotRepository(ctrl *gomock.Controller) *MockDateSpotRepository {
	mock := &MockDateSpotRepository{ctrl: ctrl}
	mock.recorder = &MockDateSpotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDateSpotRepository) EXPECT() *MockDateSpotRepositoryMockRecorder {
	return m.recorder
}

// CountByPrefectureAndGenre mocks base method.
func (m *MockDateSpotRepository) CountByPrefectureAndGenre(ctx context.Context, prefectureID, genreID int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPrefectureAndGenre", ctx, prefectureID, genreID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPrefectureAndGenre indicates an expected call of CountByPrefectureAndGenre.
func (mr *MockDateSpotRepositoryMockRecorder) CountByPrefectureAndGenre(ctx, prefectureID, genreID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPrefectureAndGenre", reflect.TypeOf((*MockDateSpotRepository)(nil).CountByPrefectureAndGenre), ctx, prefectureID, genreID)
}

// Create mocks base method.
func (m *MockDateSpotRepository) Create(ctx context.Context, dateSpot *model.DateSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dateSpot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDateSpotRepositoryMockRecorder) Create(ctx, dateSpot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDateSpotRepository)(nil).Create), ctx, dateSpot)
}

// CreateBatch mocks base method.
func (m *MockDateSpotRepository) CreateBatch(ctx context.Context, dateSpots []*model.DateSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, dateSpots)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockDateSpotRepositoryMockRecorder) CreateBatch(ctx, dateSpots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockDateSpotRepository)(nil).CreateBatch), ctx, dateSpots)
}

// Delete mocks base method.
func (m *MockDateSpotRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDateSpotRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDateSpotRepository)(nil).Delete), ctx, id)
}

// ExistsByNormalizedNameAndPrefecture mocks base method.
func (m *MockDateSpotRepository) ExistsByNormalizedNameAndPrefecture(ctx context.Context, normalizedName string, prefectureID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNormalizedNameAndPrefecture", ctx, normalizedName, prefectureID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNormalizedNameAndPrefecture indicates an expected call of ExistsByNormalizedNameAndPrefecture.
func (mr *MockDateSpotRepositoryMockRecorder) ExistsByNormalizedNameAndPrefecture(ctx, normalizedName, prefectureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNormalizedNameAndPrefecture", reflect.TypeOf((*MockDateSpotRepository)(nil).ExistsByNormalizedNameAndPrefecture), ctx, normalizedName, prefectureID)
}

// FindByID mocks base method.
func (m *MockDateSpotRepository) FindByID(ctx context.Context, id uint) (*model.DateSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.DateSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDateSpotRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDateSpotRepository)(nil).FindByID), ctx, id)
}

// Search mocks base method.
func (m *MockDateSpotRepository) Search(ctx context.Context, params repository.DateSpotSearchParams) ([]*model.DateSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].([]*model.DateSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockDateSpotRepositoryMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockDateSpotRepository)(nil).Search), ctx, params)
}

// Update mocks base method.
func (m *MockDateSpotRepository) Update(ctx context.Context, id uint, dateSpot *model.DateSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, dateSpot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDateSpotRepositoryMockRecorder) Update(ctx, id, dateSpot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDateSpotRepository)(nil).Update), ctx, id, dateSpot)
}
