// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/date_spot_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/date_spot_repository.go -destination=internal/domain/repository/mock/date_spot_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	repository "github.com/daisuke-harada/date-courses-go/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockDateSpotRepository is a mock of DateSpotRepository interface.
type MockDateSpotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDateSpotRepositoryMockRecorder
	isgomock struct{}
}

// MockDateSpotRepositoryMockRecorder is the mock recorder for MockDateSpotRepository.
type MockDateSpotRepositoryMockRecorder struct {
	mock *MockDateSpotRepository
}

// NewMockDateSpotRepository creates a new mock instance.
func NewMockDateSpotRepository(ctrl *gomock.Controller) *MockDateSpotRepository {
	mock := &MockDateSpotRepository{ctrl: ctrl}
	mock.recorder = &MockDateSpotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDateSpotRepository) EXPECT() *MockDateSpotRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDateSpotRepository) Create(ctx context.Context, dateSpot *model.DateSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dateSpot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDateSpotRepositoryMockRecorder) Create(ctx, dateSpot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDateSpotRepository)(nil).Create), ctx, dateSpot)
}

// Search mocks base method.
func (m *MockDateSpotRepository) Search(ctx context.Context, params repository.DateSpotSearchParams) ([]*model.DateSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, params)
	ret0, _ := ret[0].([]*model.DateSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockDateSpotRepositoryMockRecorder) Search(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockDateSpotRepository)(nil).Search), ctx, params)
}
