// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/during_spot_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/during_spot_repository.go -destination=internal/domain/repository/mock/during_spot_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDuringSpotRepository is a mock of DuringSpotRepository interface.
type MockDuringSpotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDuringSpotRepositoryMockRecorder
	isgomock struct{}
}

// MockDuringSpotRepositoryMockRecorder is the mock recorder for MockDuringSpotRepository.
type MockDuringSpotRepositoryMockRecorder struct {
	mock *MockDuringSpotRepository
}

// NewMockDuringSpotRepository creates a new mock instance.
func NewMockDuringSpotRepository(ctrl *gomock.Controller) *MockDuringSpotRepository {
	mock := &MockDuringSpotRepository{ctrl: ctrl}
	mock.recorder = &MockDuringSpotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDuringSpotRepository) EXPECT() *MockDuringSpotRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDuringSpotRepository) Create(ctx context.Context, duringSpot *model.DuringSpot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, duringSpot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDuringSpotRepositoryMockRecorder) Create(ctx, duringSpot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDuringSpotRepository)(nil).Create), ctx, duringSpot)
}
