// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/relationship_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/relationship_repository.go -destination=internal/domain/repository/mock/relationship_repository.go -package=repositorymock
//

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	reflect "reflect"

	model "github.com/daisuke-harada/date-courses-go/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRelationshipRepository is a mock of RelationshipRepository interface.
type MockRelationshipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRelationshipRepositoryMockRecorder
	isgomock struct{}
}

// MockRelationshipRepositoryMockRecorder is the mock recorder for MockRelationshipRepository.
type MockRelationshipRepositoryMockRecorder struct {
	mock *MockRelationshipRepository
}

// NewMockRelationshipRepository creates a new mock instance.
func NewMockRelationshipRepository(ctrl *gomock.Controller) *MockRelationshipRepository {
	mock := &MockRelationshipRepository{ctrl: ctrl}
	mock.recorder = &MockRelationshipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationshipRepository) EXPECT() *MockRelationshipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRelationshipRepository) Create(ctx context.Context, relationship *model.Relationship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, relationship)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRelationshipRepositoryMockRecorder) Create(ctx, relationship any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRelationshipRepository)(nil).Create), ctx, relationship)
}

// DeleteByUserIDs mocks base method.
func (m *MockRelationshipRepository) DeleteByUserIDs(ctx context.Context, userID uint, followID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDs", ctx, userID, followID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDs indicates an expected call of DeleteByUserIDs.
func (mr *MockRelationshipRepositoryMockRecorder) DeleteByUserIDs(ctx, userID, followID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDs", reflect.TypeOf((*MockRelationshipRepository)(nil).DeleteByUserIDs), ctx, userID, followID)
}

// FindFollowersByUserID mocks base method.
func (m *MockRelationshipRepository) FindFollowersByUserID(ctx context.Context, userID uint) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFollowersByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFollowersByUserID indicates an expected call of FindFollowersByUserID.
func (mr *MockRelationshipRepositoryMockRecorder) FindFollowersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFollowersByUserID", reflect.TypeOf((*MockRelationshipRepository)(nil).FindFollowersByUserID), ctx, userID)
}

// FindFollowingsByUserID mocks base method.
func (m *MockRelationshipRepository) FindFollowingsByUserID(ctx context.Context, userID uint) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFollowingsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFollowingsByUserID indicates an expected call of FindFollowingsByUserID.
func (mr *MockRelationshipRepositoryMockRecorder) FindFollowingsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFollowingsByUserID", reflect.TypeOf((*MockRelationshipRepository)(nil).FindFollowingsByUserID), ctx, userID)
}
