// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	Get(ctx echo.Context) error

	// (GET /api/v1/courses)
	GetApiV1Courses(ctx echo.Context, params GetApiV1CoursesParams) error

	// (POST /api/v1/courses)
	PostApiV1Courses(ctx echo.Context) error

	// (DELETE /api/v1/courses/{id})
	DeleteApiV1CoursesId(ctx echo.Context, id int) error

	// (GET /api/v1/courses/{id})
	GetApiV1CoursesId(ctx echo.Context, id int) error

	// (POST /api/v1/date_spot_reviews)
	PostApiV1DateSpotReviews(ctx echo.Context) error

	// (DELETE /api/v1/date_spot_reviews/{id})
	DeleteApiV1DateSpotReviewsId(ctx echo.Context, id int) error

	// (PUT /api/v1/date_spot_reviews/{id})
	PutApiV1DateSpotReviewsId(ctx echo.Context, id int) error

	// (GET /api/v1/date_spots)
	GetApiV1DateSpots(ctx echo.Context, params GetApiV1DateSpotsParams) error

	// (POST /api/v1/date_spots)
	PostApiV1DateSpots(ctx echo.Context) error

	// (DELETE /api/v1/date_spots/{id})
	DeleteApiV1DateSpotsId(ctx echo.Context, id int) error

	// (GET /api/v1/date_spots/{id})
	GetApiV1DateSpotsId(ctx echo.Context, id int) error

	// (PUT /api/v1/date_spots/{id})
	PutApiV1DateSpotsId(ctx echo.Context, id int) error

	// (GET /api/v1/genres/{id})
	GetApiV1GenresId(ctx echo.Context, id int) error

	// (POST /api/v1/login)
	PostApiV1Login(ctx echo.Context) error

	// (GET /api/v1/prefectures/{id})
	GetApiV1PrefecturesId(ctx echo.Context, id int) error

	// (POST /api/v1/relationships)
	PostApiV1Relationships(ctx echo.Context) error

	// (DELETE /api/v1/relationships/{current_user_id}/{other_user_id})
	DeleteApiV1RelationshipsCurrentUserIdOtherUserId(ctx echo.Context, currentUserId int, otherUserId int) error

	// (POST /api/v1/signup)
	PostApiV1Signup(ctx echo.Context) error

	// (GET /api/v1/top)
	GetApiV1Top(ctx echo.Context) error

	// (GET /api/v1/users)
	GetApiV1Users(ctx echo.Context, params GetApiV1UsersParams) error

	// (DELETE /api/v1/users/{id})
	DeleteApiV1UsersId(ctx echo.Context, id int) error

	// (GET /api/v1/users/{id})
	GetApiV1UsersId(ctx echo.Context, id int) error

	// (PUT /api/v1/users/{id})
	PutApiV1UsersId(ctx echo.Context, id int) error

	// (GET /api/v1/users/{user_id}/followers)
	GetApiV1UsersUserIdFollowers(ctx echo.Context, userId int) error

	// (GET /api/v1/users/{user_id}/followings)
	GetApiV1UsersUserIdFollowings(ctx echo.Context, userId int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Get converts echo context to params.
func (w *ServerInterfaceWrapper) Get(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Get(ctx)
	return err
}

// GetApiV1Courses converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1Courses(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1CoursesParams
	// ------------- Optional query parameter "prefecture_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "prefecture_id", ctx.QueryParams(), &params.PrefectureId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter prefecture_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1Courses(ctx, params)
	return err
}

// PostApiV1Courses converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Courses(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Courses(ctx)
	return err
}

// DeleteApiV1CoursesId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1CoursesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1CoursesId(ctx, id)
	return err
}

// GetApiV1CoursesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1CoursesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1CoursesId(ctx, id)
	return err
}

// PostApiV1DateSpotReviews converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1DateSpotReviews(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1DateSpotReviews(ctx)
	return err
}

// DeleteApiV1DateSpotReviewsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1DateSpotReviewsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1DateSpotReviewsId(ctx, id)
	return err
}

// PutApiV1DateSpotReviewsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1DateSpotReviewsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1DateSpotReviewsId(ctx, id)
	return err
}

// GetApiV1DateSpots converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1DateSpots(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1DateSpotsParams
	// ------------- Optional query parameter "date_spot_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date_spot_name", ctx.QueryParams(), &params.DateSpotName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date_spot_name: %s", err))
	}

	// ------------- Optional query parameter "prefecture_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "prefecture_id", ctx.QueryParams(), &params.PrefectureId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter prefecture_id: %s", err))
	}

	// ------------- Optional query parameter "genre_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "genre_id", ctx.QueryParams(), &params.GenreId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter genre_id: %s", err))
	}

	// ------------- Optional query parameter "come_time" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "come_time", ctx.QueryParams(), &params.ComeTime, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter come_time: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1DateSpots(ctx, params)
	return err
}

// PostApiV1DateSpots converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1DateSpots(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1DateSpots(ctx)
	return err
}

// DeleteApiV1DateSpotsId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1DateSpotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1DateSpotsId(ctx, id)
	return err
}

// GetApiV1DateSpotsId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1DateSpotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1DateSpotsId(ctx, id)
	return err
}

// PutApiV1DateSpotsId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1DateSpotsId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1DateSpotsId(ctx, id)
	return err
}

// GetApiV1GenresId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1GenresId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1GenresId(ctx, id)
	return err
}

// PostApiV1Login converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Login(ctx)
	return err
}

// GetApiV1PrefecturesId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1PrefecturesId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1PrefecturesId(ctx, id)
	return err
}

// PostApiV1Relationships converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Relationships(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Relationships(ctx)
	return err
}

// DeleteApiV1RelationshipsCurrentUserIdOtherUserId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1RelationshipsCurrentUserIdOtherUserId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "current_user_id" -------------
	var currentUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "current_user_id", ctx.Param("current_user_id"), &currentUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter current_user_id: %s", err))
	}

	// ------------- Path parameter "other_user_id" -------------
	var otherUserId int

	err = runtime.BindStyledParameterWithOptions("simple", "other_user_id", ctx.Param("other_user_id"), &otherUserId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter other_user_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1RelationshipsCurrentUserIdOtherUserId(ctx, currentUserId, otherUserId)
	return err
}

// PostApiV1Signup converts echo context to params.
func (w *ServerInterfaceWrapper) PostApiV1Signup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostApiV1Signup(ctx)
	return err
}

// GetApiV1Top converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1Top(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1Top(ctx)
	return err
}

// GetApiV1Users converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1Users(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1UsersParams
	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", ctx.QueryParams(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1Users(ctx, params)
	return err
}

// DeleteApiV1UsersId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApiV1UsersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApiV1UsersId(ctx, id)
	return err
}

// GetApiV1UsersId converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1UsersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1UsersId(ctx, id)
	return err
}

// PutApiV1UsersId converts echo context to params.
func (w *ServerInterfaceWrapper) PutApiV1UsersId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutApiV1UsersId(ctx, id)
	return err
}

// GetApiV1UsersUserIdFollowers converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1UsersUserIdFollowers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1UsersUserIdFollowers(ctx, userId)
	return err
}

// GetApiV1UsersUserIdFollowings converts echo context to params.
func (w *ServerInterfaceWrapper) GetApiV1UsersUserIdFollowings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetApiV1UsersUserIdFollowings(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/", wrapper.Get, options.OperationMiddlewares["Get"]...)
	router.GET(options.BaseURL+"/api/v1/courses", wrapper.GetApiV1Courses, options.OperationMiddlewares["GetApiV1Courses"]...)
	router.POST(options.BaseURL+"/api/v1/courses", wrapper.PostApiV1Courses, options.OperationMiddlewares["PostApiV1Courses"]...)
	router.DELETE(options.BaseURL+"/api/v1/courses/:id", wrapper.DeleteApiV1CoursesId, options.OperationMiddlewares["DeleteApiV1CoursesId"]...)
	router.GET(options.BaseURL+"/api/v1/courses/:id", wrapper.GetApiV1CoursesId, options.OperationMiddlewares["GetApiV1CoursesId"]...)
	router.POST(options.BaseURL+"/api/v1/date_spot_reviews", wrapper.PostApiV1DateSpotReviews, options.OperationMiddlewares["PostApiV1DateSpotReviews"]...)
	router.DELETE(options.BaseURL+"/api/v1/date_spot_reviews/:id", wrapper.DeleteApiV1DateSpotReviewsId, options.OperationMiddlewares["DeleteApiV1DateSpotReviewsId"]...)
	router.PUT(options.BaseURL+"/api/v1/date_spot_reviews/:id", wrapper.PutApiV1DateSpotReviewsId, options.OperationMiddlewares["PutApiV1DateSpotReviewsId"]...)
	router.GET(options.BaseURL+"/api/v1/date_spots", wrapper.GetApiV1DateSpots, options.OperationMiddlewares["GetApiV1DateSpots"]...)
	router.POST(options.BaseURL+"/api/v1/date_spots", wrapper.PostApiV1DateSpots, options.OperationMiddlewares["PostApiV1DateSpots"]...)
	router.DELETE(options.BaseURL+"/api/v1/date_spots/:id", wrapper.DeleteApiV1DateSpotsId, options.OperationMiddlewares["DeleteApiV1DateSpotsId"]...)
	router.GET(options.BaseURL+"/api/v1/date_spots/:id", wrapper.GetApiV1DateSpotsId, options.OperationMiddlewares["GetApiV1DateSpotsId"]...)
	router.PUT(options.BaseURL+"/api/v1/date_spots/:id", wrapper.PutApiV1DateSpotsId, options.OperationMiddlewares["PutApiV1DateSpotsId"]...)
	router.GET(options.BaseURL+"/api/v1/genres/:id", wrapper.GetApiV1GenresId, options.OperationMiddlewares["GetApiV1GenresId"]...)
	router.POST(options.BaseURL+"/api/v1/login", wrapper.PostApiV1Login, options.OperationMiddlewares["PostApiV1Login"]...)
	router.GET(options.BaseURL+"/api/v1/prefectures/:id", wrapper.GetApiV1PrefecturesId, options.OperationMiddlewares["GetApiV1PrefecturesId"]...)
	router.POST(options.BaseURL+"/api/v1/relationships", wrapper.PostApiV1Relationships, options.OperationMiddlewares["PostApiV1Relationships"]...)
	router.DELETE(options.BaseURL+"/api/v1/relationships/:current_user_id/:other_user_id", wrapper.DeleteApiV1RelationshipsCurrentUserIdOtherUserId, options.OperationMiddlewares["DeleteApiV1RelationshipsCurrentUserIdOtherUserId"]...)
	router.POST(options.BaseURL+"/api/v1/signup", wrapper.PostApiV1Signup, options.OperationMiddlewares["PostApiV1Signup"]...)
	router.GET(options.BaseURL+"/api/v1/top", wrapper.GetApiV1Top, options.OperationMiddlewares["GetApiV1Top"]...)
	router.GET(options.BaseURL+"/api/v1/users", wrapper.GetApiV1Users, options.OperationMiddlewares["GetApiV1Users"]...)
	router.DELETE(options.BaseURL+"/api/v1/users/:id", wrapper.DeleteApiV1UsersId, options.OperationMiddlewares["DeleteApiV1UsersId"]...)
	router.GET(options.BaseURL+"/api/v1/users/:id", wrapper.GetApiV1UsersId, options.OperationMiddlewares["GetApiV1UsersId"]...)
	router.PUT(options.BaseURL+"/api/v1/users/:id", wrapper.PutApiV1UsersId, options.OperationMiddlewares["PutApiV1UsersId"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/followers", wrapper.GetApiV1UsersUserIdFollowers, options.OperationMiddlewares["GetApiV1UsersUserIdFollowers"]...)
	router.GET(options.BaseURL+"/api/v1/users/:user_id/followings", wrapper.GetApiV1UsersUserIdFollowings, options.OperationMiddlewares["GetApiV1UsersUserIdFollowings"]...)

}
