// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CourseFormRequestDataAuthority.
const (
	CourseFormRequestDataAuthorityEmpty CourseFormRequestDataAuthority = "公開"
	CourseFormRequestDataAuthorityN1    CourseFormRequestDataAuthority = "非公開"
)

// Defines values for CourseFormRequestDataTravelMode.
const (
	DRIVING CourseFormRequestDataTravelMode = "DRIVING"
	WALKING CourseFormRequestDataTravelMode = "WALKING"
)

// Defines values for Gender.
const (
	GenderEmpty Gender = "男性"
	GenderN1    Gender = "女性"
)

// AreaData defines model for AreaData.
type AreaData struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// CourseFormRequestData defines model for CourseFormRequestData.
type CourseFormRequestData struct {
	Authority  CourseFormRequestDataAuthority  `json:"authority"`
	DateSpots  []int                           `json:"date_spots"`
	TravelMode CourseFormRequestDataTravelMode `json:"travel_mode"`
	UserId     int                             `json:"user_id"`
}

// CourseFormRequestDataAuthority defines model for CourseFormRequestData.Authority.
type CourseFormRequestDataAuthority string

// CourseFormRequestDataTravelMode defines model for CourseFormRequestData.TravelMode.
type CourseFormRequestDataTravelMode string

// CourseFormResponseData defines model for CourseFormResponseData.
type CourseFormResponseData struct {
	CourseId int `json:"course_id"`
}

// CourseResponseData defines model for CourseResponseData.
type CourseResponseData struct {
	Authority                  string                `json:"authority"`
	DateSpots                  []DateSpotSummaryData `json:"date_spots"`
	Id                         int                   `json:"id"`
	NoDuplicatePrefectureNames []string              `json:"no_duplicate_prefecture_names"`
	TravelMode                 string                `json:"travel_mode"`
	User                       UserData              `json:"user"`
}

// DateSpotData defines model for DateSpotData.
type DateSpotData struct {
	AverageRate float32   `json:"average_rate"`
	ClosingTime time.Time `json:"closing_time"`
	CreatedAt   time.Time `json:"created_at"`
	GenreId     int       `json:"genre_id"`
	Id          int       `json:"id"`
	Image       ImageData `json:"image"`
	Name        string    `json:"name"`
	OpeningTime time.Time `json:"opening_time"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// DateSpotFormRequestData defines model for DateSpotFormRequestData.
type DateSpotFormRequestData struct {
	CityName     string     `json:"city_name"`
	ClosingTime  time.Time  `json:"closing_time"`
	GenreId      int        `json:"genre_id"`
	Image        ImageData1 `json:"image"`
	Name         string     `json:"name"`
	OpeningTime  time.Time  `json:"opening_time"`
	PrefectureId int        `json:"prefecture_id"`
}

// DateSpotFormResponseData defines model for DateSpotFormResponseData.
type DateSpotFormResponseData struct {
	DateSpotId int `json:"date_spot_id"`
}

// DateSpotReviewData defines model for DateSpotReviewData.
type DateSpotReviewData struct {
	Content  string       `json:"content"`
	DateSpot DateSpotData `json:"date_spot"`
	Id       int          `json:"id"`
	Rate     float32      `json:"rate"`
}

// DateSpotReviewFormRequestData defines model for DateSpotReviewFormRequestData.
type DateSpotReviewFormRequestData struct {
	Content    string  `json:"content"`
	DateSpotId int     `json:"date_spot_id"`
	Rate       float32 `json:"rate"`
	UserId     int     `json:"user_id"`
}

// DateSpotReviewResponseData defines model for DateSpotReviewResponseData.
type DateSpotReviewResponseData struct {
	DateSpotReviews   []DateSpotShowResponseDataDateSpotReviewsInner `json:"date_spot_reviews"`
	ReviewAverageRate float32                                        `json:"review_average_rate"`
}

// DateSpotShowResponseData defines model for DateSpotShowResponseData.
type DateSpotShowResponseData struct {
	DateSpot          DateSpotSummaryData                            `json:"date_spot"`
	DateSpotReviews   []DateSpotShowResponseDataDateSpotReviewsInner `json:"date_spot_reviews"`
	ReviewAverageRate float32                                        `json:"review_average_rate"`
}

// DateSpotShowResponseDataDateSpotReviewsInner defines model for DateSpotShowResponseData_date_spot_reviews_inner.
type DateSpotShowResponseDataDateSpotReviewsInner struct {
	Content    *string   `json:"content"`
	DateSpotId int       `json:"date_spot_id"`
	Id         int       `json:"id"`
	Rate       *float32  `json:"rate"`
	UserGender string    `json:"user_gender"`
	UserId     int       `json:"user_id"`
	UserImage  ImageData `json:"user_image"`
	UserName   string    `json:"user_name"`
}

// DateSpotSummaryData defines model for DateSpotSummaryData.
type DateSpotSummaryData struct {
	AverageRate       float32      `json:"average_rate"`
	CityName          string       `json:"city_name"`
	DateSpot          DateSpotData `json:"date_spot"`
	GenreName         string       `json:"genre_name"`
	Id                int          `json:"id"`
	Latitude          float32      `json:"latitude"`
	Longitude         float32      `json:"longitude"`
	PrefectureName    string       `json:"prefecture_name"`
	ReviewTotalNumber int          `json:"review_total_number"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// ErrorMessages エラーメッセージの配列
	ErrorMessages []string `json:"errorMessages"`
}

// FollowReauestData defines model for FollowReauestData.
type FollowReauestData struct {
	CurrentUserId  int `json:"current_user_id"`
	FollowedUserId int `json:"followed_user_id"`
}

// FollowResponseData defines model for FollowResponseData.
type FollowResponseData struct {
	CurrentUser  UserResponseData   `json:"current_user"`
	FollowedUser UserResponseData   `json:"followed_user"`
	Users        []UserResponseData `json:"users"`
}

// Gender defines model for Gender.
type Gender string

// GenreData defines model for GenreData.
type GenreData struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// ImageData defines model for ImageData.
type ImageData struct {
	Url *string `json:"url"`
}

// ImageData1 defines model for ImageData_1.
type ImageData1 struct {
	Url *openapi_types.File `json:"url"`
}

// LoginResponseData defines model for LoginResponseData.
type LoginResponseData struct {
	LoginStatus bool     `json:"login_status"`
	Token       string   `json:"token"`
	User        UserData `json:"user"`
}

// PrefectureData defines model for PrefectureData.
type PrefectureData struct {
	AreaId int    `json:"area_id"`
	Id     int    `json:"id"`
	Name   string `json:"name"`
}

// RelationShipResponsData defines model for RelationShipResponsData.
type RelationShipResponsData struct {
	UserName string             `json:"user_name"`
	Users    []UserResponseData `json:"users"`
}

// SignUpResponseData defines model for SignUpResponseData.
type SignUpResponseData struct {
	LoginStatus bool             `json:"login_status"`
	Token       string           `json:"token"`
	User        UserResponseData `json:"user"`
}

// SigninFormRequestData defines model for SigninFormRequestData.
type SigninFormRequestData struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// SignupFormRequestData defines model for SignupFormRequestData.
type SignupFormRequestData struct {
	Email                string              `json:"email"`
	Gender               Gender              `json:"gender"`
	Image                *openapi_types.File `json:"image,omitempty"`
	Name                 string              `json:"name"`
	Password             string              `json:"password"`
	PasswordConfirmation string              `json:"password_confirmation"`
}

// TopResponseData defines model for TopResponseData.
type TopResponseData struct {
	Areas           []AreaData            `json:"areas"`
	DateSpots       []DateSpotSummaryData `json:"date_spots"`
	Genres          []GenreData           `json:"genres"`
	MainGenres      []GenreData           `json:"main_genres"`
	MainPrefectures []PrefectureData      `json:"main_prefectures"`
}

// UnFollowResponseData defines model for UnFollowResponseData.
type UnFollowResponseData struct {
	CurrentUser    UserResponseData   `json:"current_user"`
	UnfollowedUser UserResponseData   `json:"unfollowed_user"`
	Users          []UserResponseData `json:"users"`
}

// UserData defines model for UserData.
type UserData struct {
	Admin  bool                `json:"admin"`
	Email  openapi_types.Email `json:"email"`
	Gender Gender              `json:"gender"`
	Id     int                 `json:"id"`
	Image  ImageData           `json:"image"`
	Name   string              `json:"name"`
}

// UserFormRequestData defines model for UserFormRequestData.
type UserFormRequestData struct {
	Email                openapi_types.Email `json:"email"`
	Gender               Gender              `json:"gender"`
	Id                   string              `json:"id"`
	Image                *openapi_types.File `json:"image,omitempty"`
	Name                 string              `json:"name"`
	Password             string              `json:"password"`
	PasswordConfirmation string              `json:"password_confirmation"`
}

// UserResponseData defines model for UserResponseData.
type UserResponseData struct {
	Admin           bool                 `json:"admin"`
	Courses         []CourseResponseData `json:"courses"`
	DateSpotReviews []DateSpotReviewData `json:"date_spot_reviews"`
	Email           string               `json:"email"`
	FollowerIds     []int                `json:"followerIds"`
	FollowingIds    []int                `json:"followingIds"`
	Gender          Gender               `json:"gender"`
	Id              int                  `json:"id"`
	Image           ImageData            `json:"image"`
	Name            string               `json:"name"`
}

// WelcomeResponseData defines model for WelcomeResponseData.
type WelcomeResponseData struct {
	Message string `json:"message"`
}

// ApiV1GenresIdGet200Response defines model for _api_v1_genres__id__get_200_response.
type ApiV1GenresIdGet200Response struct {
	DateSpots []DateSpotSummaryData `json:"date_spots"`
}

// GetApiV1CoursesParams defines parameters for GetApiV1Courses.
type GetApiV1CoursesParams struct {
	PrefectureId *int `form:"prefecture_id,omitempty" json:"prefecture_id,omitempty"`
}

// GetApiV1DateSpotsParams defines parameters for GetApiV1DateSpots.
type GetApiV1DateSpotsParams struct {
	DateSpotName *string `form:"date_spot_name,omitempty" json:"date_spot_name,omitempty"`
	PrefectureId *int    `form:"prefecture_id,omitempty" json:"prefecture_id,omitempty"`
	GenreId      *int    `form:"genre_id,omitempty" json:"genre_id,omitempty"`
	ComeTime     *string `form:"come_time,omitempty" json:"come_time,omitempty"`
}

// GetApiV1UsersParams defines parameters for GetApiV1Users.
type GetApiV1UsersParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// PostApiV1CoursesFormdataRequestBody defines body for PostApiV1Courses for application/x-www-form-urlencoded ContentType.
type PostApiV1CoursesFormdataRequestBody = CourseFormRequestData

// PostApiV1DateSpotReviewsMultipartRequestBody defines body for PostApiV1DateSpotReviews for multipart/form-data ContentType.
type PostApiV1DateSpotReviewsMultipartRequestBody = DateSpotReviewFormRequestData

// PutApiV1DateSpotReviewsIdMultipartRequestBody defines body for PutApiV1DateSpotReviewsId for multipart/form-data ContentType.
type PutApiV1DateSpotReviewsIdMultipartRequestBody = DateSpotReviewFormRequestData

// PostApiV1DateSpotsMultipartRequestBody defines body for PostApiV1DateSpots for multipart/form-data ContentType.
type PostApiV1DateSpotsMultipartRequestBody = DateSpotFormRequestData

// PutApiV1DateSpotsIdMultipartRequestBody defines body for PutApiV1DateSpotsId for multipart/form-data ContentType.
type PutApiV1DateSpotsIdMultipartRequestBody = DateSpotFormRequestData

// PostApiV1LoginJSONRequestBody defines body for PostApiV1Login for application/json ContentType.
type PostApiV1LoginJSONRequestBody = SigninFormRequestData

// PostApiV1RelationshipsFormdataRequestBody defines body for PostApiV1Relationships for application/x-www-form-urlencoded ContentType.
type PostApiV1RelationshipsFormdataRequestBody = FollowReauestData

// PostApiV1SignupMultipartRequestBody defines body for PostApiV1Signup for multipart/form-data ContentType.
type PostApiV1SignupMultipartRequestBody = SignupFormRequestData

// PutApiV1UsersIdMultipartRequestBody defines body for PutApiV1UsersId for multipart/form-data ContentType.
type PutApiV1UsersIdMultipartRequestBody = UserFormRequestData
