// Code generated by auth_generator.go DO NOT EDIT.
// Source: api/resolved/openapi/openapi.yaml
// Run "make gen" to regenerate.
package openapi

// bearerAuthRoutes は Bearer JWT 認証が必要なルートの集合です。
// キー形式: "METHOD /echo/path/pattern"
var bearerAuthRoutes = map[string]struct{}{
	"POST /api/v1/courses": {},
	"DELETE /api/v1/courses/:id": {},
	"POST /api/v1/date_spot_reviews": {},
	"DELETE /api/v1/date_spot_reviews/:id": {},
	"PUT /api/v1/date_spot_reviews/:id": {},
	"POST /api/v1/date_spots": {},
	"DELETE /api/v1/date_spots/:id": {},
	"PUT /api/v1/date_spots/:id": {},
	"POST /api/v1/relationships": {},
	"DELETE /api/v1/relationships/:current_user_id/:other_user_id": {},
	"DELETE /api/v1/users/:id": {},
	"PUT /api/v1/users/:id": {},
	"GET /api/v1/users/:user_id/followers": {},
	"GET /api/v1/users/:user_id/followings": {},
}

// RequiresBearerAuth は指定の HTTP メソッドと Echo ルートパターンが
// Bearer JWT 認証を必要とするかどうかを返します。
// middleware.JWTAuthMiddleware から呼び出されます。
func RequiresBearerAuth(method, echoPath string) bool {
	_, ok := bearerAuthRoutes[method+" "+echoPath]
	return ok
}
